# Generated by Django 3.2 on 2023-05-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='photo',
            field=models.ImageField(default=1, upload_to='Media/img'),
            preserve_default=False,
        ),
    ]
